[tool.poetry]
name = "python-gql"
version = "0.1.0"
description = "Python schema-first and auto-generate class graphql server"
authors = ["syfun <sunyu418@gmail.com>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "gql" }
]

[tool.poetry.dependencies]
python = "^3.7"
starlette = "^0.12"
graphql-core = "^3.0"
fire = "^0.2"

[tool.poetry.dev-dependencies]
black = "19.3b0"
isort = "^4.3"
flake8 = "^3.7"
pre-commit = "^1.20"

[tool.poetry.scripts]
gqlgen = 'gql.cli.main:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
